
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HIJOS = 11;
  public static final int FT_SOLID = 22;
  public static final int C_ROJO = 18;
  public static final int SH = 4;
  public static final int SH_CUADRADO = 12;
  public static final int SH_RECTANGULO = 15;
  public static final int ETIQUETA_VALOR2 = 37;
  public static final int ETIQUETA_VALOR1 = 36;
  public static final int CORCHETE_C = 30;
  public static final int CORCHETE_A = 28;
  public static final int LLAVE_C = 29;
  public static final int LLAVE_A = 27;
  public static final int C_AZUL = 16;
  public static final int IDENTIFICADOR = 35;
  public static final int C_AMARILLO = 19;
  public static final int IGUAL = 31;
  public static final int ARISTA = 9;
  public static final int FT_DASHED = 21;
  public static final int DIR_FORWARD = 24;
  public static final int PUNTO_COMA = 33;
  public static final int EOF = 0;
  public static final int DIR_NONE = 23;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int C_VERDE = 17;
  public static final int COMENTARIO = 34;
  public static final int DIR_BOTH = 26;
  public static final int DIRECCION = 10;
  public static final int COLOR = 6;
  public static final int ARBOL = 2;
  public static final int COLOR_FUENTE = 7;
  public static final int DIR_BACK = 25;
  public static final int SH_CIRCULO = 13;
  public static final int NODO = 3;
  public static final int ETIQUETA = 5;
  public static final int SH_DOBLECIRCULO = 14;
  public static final int FT_BOLD = 20;
  public static final int FUENTE = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ARBOL",
  "NODO",
  "SH",
  "ETIQUETA",
  "COLOR",
  "COLOR_FUENTE",
  "FUENTE",
  "ARISTA",
  "DIRECCION",
  "HIJOS",
  "SH_CUADRADO",
  "SH_CIRCULO",
  "SH_DOBLECIRCULO",
  "SH_RECTANGULO",
  "C_AZUL",
  "C_VERDE",
  "C_ROJO",
  "C_AMARILLO",
  "FT_BOLD",
  "FT_DASHED",
  "FT_SOLID",
  "DIR_NONE",
  "DIR_FORWARD",
  "DIR_BACK",
  "DIR_BOTH",
  "LLAVE_A",
  "CORCHETE_A",
  "LLAVE_C",
  "CORCHETE_C",
  "IGUAL",
  "COMA",
  "PUNTO_COMA",
  "COMENTARIO",
  "IDENTIFICADOR",
  "ETIQUETA_VALOR1",
  "ETIQUETA_VALOR2"
  };
}

